---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{include "deployment.name" .}}
  namespace: {{.Release.Namespace}}
spec:
  replicas: 1
  selector:
    matchLabels: &match-labels
      control-plane: {{include "deployment.name" .}}
  template:
    metadata:
      labels: *match-labels
    spec:
      containers:
        - name: manager
          image: '{{.Values.image.repository}}:{{.Values.image.tag | default "latest"}}'
          imagePullPolicy: {{.Values.image.pullPolicy | default "Always"}}

          args:
            - --health-probe-bind-address=:8081
            - --metrics-bind-address=127.0.0.1:8080
            - --leader-elect

          env:
            - name: MAX_CONCURRENT_RECONCILES
              value: "5"

            - name: HELM_JOB_IMAGE
              value: "ghcr.io/kloudlite/kloudlite/operator/workers/helm-job-runner:v1.1.5"

          livenessProbe:
            httpGet:
              path: /healthz
              port: 8081
            initialDelaySeconds: 15
            periodSeconds: 20

          readinessProbe:
            httpGet:
              path: /readyz
              port: 8081
            initialDelaySeconds: 5
            periodSeconds: 10

          resources:
            limits:
              cpu: 200m
              memory: 200Mi
            requests:
              cpu: 150m
              memory: 150Mi

          securityContext:
            allowPrivilegeEscalation: false
            capabilities:
              drop:
                - ALL

      securityContext:
        runAsNonRoot: true
      # serviceAccountName: "kloudlite-cluster-admin"
      serviceAccountName: "kloudlite-sa"
      terminationGracePeriodSeconds: 10


