---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: manager-role
rules:
- apiGroups:
  - ""
  resources:
  - persistentvolumeclaim
  - secrets
  - services
  verbs:
  - create
  - delete
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - apps
  resources:
  - statefulsets
  verbs:
  - create
  - delete
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - plugin-mongodb.kloudlite.github.com
  resources:
  - standaloneservices
  verbs:
  - create
  - delete
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - plugin-mongodb.kloudlite.github.com
  resources:
  - standaloneservices/finalizers
  verbs:
  - update
- apiGroups:
  - plugin-mongodb.kloudlite.github.com
  resources:
  - standaloneservices/status
  verbs:
  - get
  - patch
  - update
