# permissions for end users to edit standaloneservices.
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  labels:
    app.kubernetes.io/name: plugin-mongodb
    app.kubernetes.io/managed-by: kustomize
  name: standaloneservice-editor-role
rules:
- apiGroups:
  - plugin-mongodb.kloudlite.github.com
  resources:
  - standaloneservices
  verbs:
  - create
  - delete
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - plugin-mongodb.kloudlite.github.com
  resources:
  - standaloneservices/status
  verbs:
  - get
